version: '3.4'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=simpledb
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
  vonagedemo:
    image: node:14.18.0-alpine
    working_dir: /app
    env_file:
      - .env
    volumes:
      - ./:/app/
    ports:
      - 3000:3000
    command:
      - /bin/sh
      - -c
      - npm i -g nodemon sequelize-cli && apk --no-cache add g++ ca-certificates make python3 && npm i && npm run start
    depends_on:
      - db


